name: Deploy WAR to JBoss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    env:
      JBOSS_ENDPOINT: ${{ secrets.JBOSS_ENDPOINT }}
      JBOSS_USERNAME: ${{ secrets.JBOSS_USERNAME }}
      JBOSS_PASSWORD: ${{ secrets.JBOSS_PASSWORD }}
      WAR_PATH: 'dist/helloworld.war'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'    
       
      - name: Deploy to Jboss
        run: |
          curl -u $JBOSS_USERNAME $JBOSS_PASSWORD $WAR_PATH $JBOSS_ENDPOINT/management-webapp/undeploy?name=$($WAR_PATH)
          sleep 5
          curl -u $JBOSS_USERNAME $JBOSS_PASSWORD $WAR_PATH $JBOSS_ENDPOINT/management-webapp/deploy?name=$($WAR_PATH)