name: Deploy WAR to JBoss

#on:
  #push:
    #branches:
      #- master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/helloworld.war
          remote: demo/actions/helloworld.war
          host: ${{secrets.JBOSS_ENDPOINT}}
          username: ${{ secrets.JBOSS_USERNAME }}
          password: ${{ secrets.JBOSS_PASSWORD }}
      - name: run a script on server (start the application)
        if: always()
        uses: fifsky/ssh-actions@master
        with:
          command: |
            cd demo/actions/ && java -jar helloworld.war &
          host: ${{secrets.JBOSS_ENDPOINT}}
          username: ${{ secrets.JBOSS_USERNAME }}
          password: ${{ secrets.JBOSS_PASSWORD }}
          args: "-tt"