name: Deploy WAR to Local JBoss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Deploy WAR to Local JBoss
        env:
          JBOSS_HOME: 'C:\Users\somas\EAP-7.4.0'
          JBOSS_CONFIG: 'standalone'
          WAR_PATH: 'dist/helloworld.war'
        run: |
          # Set the JBOSS_HOME environment variable
          echo "export JBOSS_HOME=${JBOSS_HOME}" >> $GITHUB_ENV

          # Build the JBoss CLI command
          JBOSS_CLI="${JBOSS_HOME}/bin/jboss-cli.sh"
          DEPLOY_COMMAND="/server=${JBOSS_CONFIG}:deploy ${WAR_PATH}"
          
          # Execute the JBoss CLI command
          $JBOSS_CLI --connect --command="${DEPLOY_COMMAND}"
